In [1]:
import numpy as np

H = np.array([[0, -1, -1, 1, 1, 1],
              [-1, 0, 1, -1, -1, -1],
              [-1, 1, 0, -1, -1, -1],
              [1, -1, -1, 0, 1, 1],
              [1, -1, -1, 1, 0, 1],
              [1, -1, -1, 1, 1, 0]])
a = np.ones(6).reshape(-1,1)

In [5]:
a[np.dot(H, a)<=0]=-1

In [6]:
a

array([[ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [7]:
a[np.dot(H, a)<=0]=-1

In [8]:
a

array([[ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [9]:
H = np.array([[0, -1, -1, 1, 1, 1],
              [-1, 0, 1, -1, -1, -1],
              [-1, 1, 0, -1, -1, -1],
              [1, -1, -1, 0, 1, 1],
              [1, -1, -1, 1, 0, 1],
              [1, -1, -1, 1, 1, 0]])

In [18]:
s_list = []

for i in range(2):
    for j in range(2):
        for k in range(2):
            for l in range(2):
                for m in range(2):
                    for n in range(2):
#                         print(i)
                        s = np.empty(6)
                        s[0] = 1 if i==1 else -1
                        s[1] = 1 if j==1 else -1
                        s[2] = 1 if k==1 else -1
                        s[3] = 1 if l==1 else -1
                        s[4] = 1 if m==1 else -1
                        s[5] = 1 if n==1 else -1
                        s_list.append(s)

In [19]:
def cal_energy(H, s):
    e = 0
    for i in range(6):
        for j in range(i):
            e += H[i][j]*s[i]*s[j]
    return e*-1

In [25]:
score_list = []
for s in s_list:
    score_list.append(cal_energy(H, s));
# score_list.sort()

In [27]:
np.argmin(score_list)

24

In [28]:
s_list[24]

array([-1.,  1.,  1., -1., -1., -1.])