In [1]:
import numpy as np

In [2]:
x = np.arange(80).reshape((8,10))
y = np.zeros((8,10))
y[:,4] = 1

exps = np.exp(x - np.max(x, axis = 1,keepdims = True))
softmax = exps/np.sum(exps,axis =1,keepdims = True)
loss = -np.sum(y*softmax, axis = 1)

In [3]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [4]:
np.max(x, axis = 1, keepdims = True)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79]])

In [5]:
np.exp(x - np.max(x, axis = 1,keepdims = True))

array([[1.23409804e-04, 3.35462628e-04, 9.11881966e-04, 2.47875218e-03,
        6.73794700e-03, 1.83156389e-02, 4.97870684e-02, 1.35335283e-01,
        3.67879441e-01, 1.00000000e+00],
       [1.23409804e-04, 3.35462628e-04, 9.11881966e-04, 2.47875218e-03,
        6.73794700e-03, 1.83156389e-02, 4.97870684e-02, 1.35335283e-01,
        3.67879441e-01, 1.00000000e+00],
       [1.23409804e-04, 3.35462628e-04, 9.11881966e-04, 2.47875218e-03,
        6.73794700e-03, 1.83156389e-02, 4.97870684e-02, 1.35335283e-01,
        3.67879441e-01, 1.00000000e+00],
       [1.23409804e-04, 3.35462628e-04, 9.11881966e-04, 2.47875218e-03,
        6.73794700e-03, 1.83156389e-02, 4.97870684e-02, 1.35335283e-01,
        3.67879441e-01, 1.00000000e+00],
       [1.23409804e-04, 3.35462628e-04, 9.11881966e-04, 2.47875218e-03,
        6.73794700e-03, 1.83156389e-02, 4.97870684e-02, 1.35335283e-01,
        3.67879441e-01, 1.00000000e+00],
       [1.23409804e-04, 3.35462628e-04, 9.11881966e-04, 2.47875218e-03,
   

In [6]:
exps/np.sum(exps,axis =0,keepdims = True)

array([[0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
        0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
        0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
        0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
        0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
        0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
        0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
        0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
        0.125]])

In [7]:
loss

array([-0.00425939, -0.00425939, -0.00425939, -0.00425939, -0.00425939,
       -0.00425939, -0.00425939, -0.00425939])

In [8]:
mean = np.mean(x, axis=0,keepdims = True)
var = np.var(x,axis=0,keepdims = True)
print(mean.shape)
print(var.shape)

(1, 10)
(1, 10)


In [9]:
eps = 1e-8
norm = (x-mean)/(var+eps)
print(norm.shape)

(8, 10)


In [10]:
gamma = np.ones((1,10))
beta = np.ones((1,10))
output = norm*gamma + beta
print(output.shape)

(8, 10)


In [11]:
seed = 123
np.random.seed(seed)
delta = np.random.randn(8,10)

In [12]:
dnorm = delta*gamma
print(dnorm)

[[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025  1.65143654
  -2.42667924 -0.42891263  1.26593626 -0.8667404 ]
 [-0.67888615 -0.09470897  1.49138963 -0.638902   -0.44398196 -0.43435128
   2.20593008  2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904 -1.25388067 -0.6377515
   0.9071052  -1.4286807  -0.14006872 -0.8617549 ]
 [-0.25561937 -2.79858911 -1.7715331  -0.69987723  0.92746243 -0.17363568
   0.00284592  0.68822271 -0.87953634  0.28362732]
 [-0.80536652 -1.72766949 -0.39089979  0.57380586  0.33858905 -0.01183049
   2.39236527  0.41291216  0.97873601  2.23814334]
 [-1.29408532 -1.03878821  1.74371223 -0.79806274  0.02968323  1.06931597
   0.89070639  1.75488618  1.49564414  1.06939267]
 [-0.77270871  0.79486267  0.31427199 -1.32626546  1.41729905  0.80723653
   0.04549008 -0.23309206 -1.19830114  0.19952407]
 [ 0.46843912 -0.83115498  1.16220405 -1.09720305 -2.12310035  1.03972709
  -0.40336604 -0.12602959 -0.83751672 -1.60596276]]


In [13]:
dbeta = np.sum(delta, axis = 0, keepdims = True)
dgamma = np.sum(delta * norm, axis = 0, keepdims = True)
print(dbeta.shape, dgamma.shape)

(1, 10) (1, 10)


In [14]:
dvar = -0.5*np.sum((x-mean)*np.power((var + eps),-3/2), axis = 0, keepdims = True)
print(dvar.shape)

(1, 10)


In [15]:
dmean = -np.sum(dnorm*np.power((var + eps),-0.5), axis = 0, keepdims = True) - 2*dvar*np.mean(x-mean, axis = 0, keepdims = True)
print(dmean.shape)

(1, 10)


In [16]:
m = len(x)
dx = dnorm*np.power((var+eps),-0.5) + dvar*(2/m*(x-mean)) + dmean/m
print(dx.shape)

(8, 10)


In [17]:
seed = 123
np.random.seed(seed)
W = np.random.randn(10,16)
b = np.random.randn(16)
np.dot(x,W) + b

array([[ 1.07145615e+01, -4.00009991e+00,  1.30909157e+01,
         5.50787971e+00, -1.36799727e+01, -1.53882417e+01,
         2.34906641e+01,  1.02455176e+00, -4.20578316e+00,
        -8.77339530e+00,  5.71843045e+00, -6.58072862e+00,
         8.98485182e+00, -8.30116590e+00,  2.65039106e+01,
         6.58102382e+00],
       [ 3.28260609e+01,  2.80252859e+01,  4.78703274e+01,
        -8.63462351e+00, -2.70072986e+01, -1.23824286e+01,
         1.55911917e+01,  1.33908914e+01,  6.64878589e+00,
        -3.87624105e+01,  1.73141903e+01, -2.06570687e+01,
         3.35861788e+01, -2.77201070e+01,  6.51411737e+01,
        -2.13084090e+01],
       [ 5.49375602e+01,  6.00506717e+01,  8.26497390e+01,
        -2.27771267e+01, -4.03346246e+01, -9.37661542e+00,
         7.69171922e+00,  2.57572310e+01,  1.75033549e+01,
        -6.87514257e+01,  2.89099501e+01, -3.47334087e+01,
         5.81875059e+01, -4.71390480e+01,  1.03778437e+02,
        -4.91978419e+01],
       [ 7.70490596e+01,  9.20760575e

In [18]:
in_feature = 10
out_feature = 16
batch_size = 8

In [19]:
dw = np.zeros((in_feature, out_feature))
print(dw)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [20]:
delta = np.random.randn(batch_size, out_feature)
print(delta.shape)

(8, 16)


In [29]:
dx = np.dot(delta, np.transpose(W))
print(dx.shape)
dW = np.dot(np.transpose(x), delta)
print(dW.shape)
db = np.dot(np.ones((1,len(x))), delta)
print(db.shape)

(8, 10)
(10, 16)
(1, 16)


In [31]:
dW.fill(0.0)
print(dW)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## MLP

In [54]:
input_size = 4
output_size = 3
hiddens = [8,16,32,64]
layers = hiddens.copy()
layers.insert(0,input_size)
layers.append(output_size)
print(hiddens)
print(layers)
for d1, d2 in zip(layers[:-1],layers[1:]):
    print(d1,d2)

[8, 16, 32, 64]
[4, 8, 16, 32, 64, 3]
4 8
8 16
16 32
32 64
64 3


In [56]:
num_bn_layers = 2
bn_layers = [d1 for d1 in hiddens[:num_bn_layers]]
print(bn_layers)

[8, 16]


In [59]:
-x

array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9],
       [-10, -11, -12, -13, -14, -15, -16, -17, -18, -19],
       [-20, -21, -22, -23, -24, -25, -26, -27, -28, -29],
       [-30, -31, -32, -33, -34, -35, -36, -37, -38, -39],
       [-40, -41, -42, -43, -44, -45, -46, -47, -48, -49],
       [-50, -51, -52, -53, -54, -55, -56, -57, -58, -59],
       [-60, -61, -62, -63, -64, -65, -66, -67, -68, -69],
       [-70, -71, -72, -73, -74, -75, -76, -77, -78, -79]])